### ISSUE TITLE
EPIC:  User Profile

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/Last-Trophy#13]
As a **site user** I can **create, read, update or delete my profile** so that **I can login into the site or update or delete my profile**

- [x] Create an Account
- [ ] View my own account
- [ ] Delete my account
- [ ] Change my password
- [ ] Reset my password if I have forgot it
