### ISSUE TITLE
EPIC: Games Searching

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/Last-Trophy#16]
As a **site user** I can **search for games to view guides that other users have written** so that **I can find new guides I haven't seen**

Potential User Stories

- [x] Search by Game Name

- [ ] Search by User name

- [ ]  Search by Trophy completion difficulty

- [x] Search by Genre
