### ISSUE TITLE
EPIC: Guides interaction

### ISSUE THREAD

**Issue by mattthughes** [mattthughes/Last-Trophy#17]
As a **logged in user** I can **make and receive feedback on the guides I have written** so that **I can answer questions or provide answers or feedback to other users**

Potential User Stories:

- [ ] Be able to answer any questions

- [ ] Be notified if a user comments or upvotes guide

- [ ] Report inappropriate comments to Admin
